version: '3.6'
services:
  influxdb:
    image: influxdb:1.8
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      TZ: "Europe/Berlin"

  chronograf:
    image: chronograf:latest
    env_file: configuration.env
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      TZ: "Europe/Berlin"
  
  grafana:
  #Custorm build image for enableding rendering!
    build:
      context: grafana
      dockerfile: docker/Dockerfile
    image: grafana
    ports:
      - '3000:3000'
    env_file: configuration.env
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/conf/grafana.ini:/usr/share/grafana/conf/defaults.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - influxdb
    environment:
      TZ: "Europe/Berlin"

  telegraf:
    image: telegraf:1.18
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125/udp'
    environment:
      TZ: "Europe/Berlin"
  
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./hass-config:/config
      - /etc/localtime:/etc/localtime:ro
    #restart: unless-stopped
    #privileged: true
    #network_mode: host
    links:
      - grafana
    ports:
      - "8123:8123"

  viessmannapi-cron:
    build:
      context: Viessmann2Influx/
      dockerfile: docker/Dockerfile
    image: viessmannapi-cron
    #entrypoint: /entrypoint.sh
    volumes:
    #  - ./Viessmann2Influx/app/:/home/app/Viessmann2Influx
      - ./Viessmann2Influx/docker/runViessmann.sh:/runViessmann.sh
      - ./Viessmann2Influx/docker/watchdog.sh:/watchdog.sh
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      TZ: "Europe/Berlin"
  
      
volumes:
  grafana-storage: {}
  influxdb-storage: {}
  chronograf-storage: {}
  #viessmann-storage: {}