{
 "title": "TableOverviewViessmann",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "api.status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"api.status\" "
    }
   ]
  },
  {
   "title": "device.serial",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"device.serial\" "
    }
   ]
  },
  {
   "title": "heating.boiler",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"heating.boiler\" "
    }
   ]
  },
  {
   "title": "heating.burners",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"heating.burners\" "
    }
   ]
  },
  {
   "title": "heating.circuits",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"heating.circuits\" "
    }
   ]
  },
  {
   "title": "heating.configuration",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"heating.configuration\" "
    }
   ]
  },
  {
   "title": "heating.device",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heating.device",
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"heating.device\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "heating.dhw",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"heating.dhw\" "
    }
   ]
  },
  {
   "title": "heating.gas",
   "type": "table",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 54 },
   "targets": [
    {
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"heating.gas\" "
    }
   ]
  },
  {
   "title": "heating.operating",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"heating.operating\" "
    }
   ]
  },
  {
   "title": "heating.sensors",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 67 },
   "targets": [
    {
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"heating.sensors\" "
    }
   ]
  },
  {
   "title": "heating.solar",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 74 },
   "targets": [
    {
     "query": "SELECT * FROM \"heizung\".\"autogen\".\"heating.solar\" "
    }
   ]
  }
 ]
}