{
 "title": "NEW_ViessmannDashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "databaseVSM", "query": "influxdb" },
   {
    "name": "devices",
    "query": "SHOW TAG VALUES FROM  \"heating.circuits\" WITH key=\"feature_branch\""
   },
   { "name": "consumption_entities", "query": "day, week, month, year\n" }
  ]
 },
 "panels": [
  {
   "title": "Notes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Title\n\n  For markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n           "
     }
    },
    {
     "title": "Panel Title",
     "type": "text",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 5 },
     "options": {
      "content": "<iframe width=\"640\" height=\"390\" src=\"https://solcast.com/embed.html?v=deu/2021-11-14/1280x720\" frameborder=\"0\" allow=\"autoplay;\" allowfullscreen></iframe>"
     }
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Serial ID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "device.serial",
     "select": [
      [
       { "params": [ "value_string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Modulation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.burners",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature_child", "operator": "=", "value": "modulation" },
      { "condition": "AND", "key": "entity", "operator": "=", "value": "value" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Runtime Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.burners",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature_child", "operator": "=", "value": "statistics" },
      { "condition": "AND", "key": "entity", "operator": "=", "value": "hours" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Burner Starts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heating.burners",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature_child", "operator": "=", "value": "statistics" },
      { "condition": "AND", "key": "entity", "operator": "=", "value": "starts" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "API Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "logger",
     "select": [
      [
       { "params": [ "apiStatus_bool" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Boiler Supply Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.boiler",
     "query": "SELECT mean(\"DomesticHotWaterStorageTemperature\") FROM \"viessmann.GazBoiler.Data\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity", "operator": "=", "value": "value" },
      {
       "condition": "AND",
       "key": "feature",
       "operator": "=",
       "value": "heating.boiler.sensors.temperature.commonSupply"
      }
     ]
    }
   ]
  },
  {
   "title": "Boiler Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.boiler",
     "query": "SELECT mean(\"DomesticHotWaterStorageTemperature\") FROM \"viessmann.GazBoiler.Data\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity", "operator": "=", "value": "value" },
      { "condition": "AND", "key": "feature", "operator": "=", "value": "heating.boiler.temperature" }
     ]
    }
   ]
  },
  {
   "title": "HotWaterStorage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heating.dhw",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "feature",
       "operator": "=",
       "value": "heating.dhw.sensors.temperature.hotWaterStorage"
      }
     ]
    }
   ]
  },
  {
   "title": "DHW Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heating.dhw",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "heating.dhw.temperature.main" }
     ]
    }
   ]
  },
  {
   "title": "Solar DHW  Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.solar",
     "query": "SELECT mean(\"DomesticHotWaterStorageTemperature\") FROM \"viessmann.GazBoiler.Data\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "feature",
       "operator": "=",
       "value": "heating.solar.sensors.temperature.dhw"
      }
     ]
    }
   ]
  },
  {
   "title": "Solar Collector Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heating.solar",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "feature",
       "operator": "=",
       "value": "heating.solar.sensors.temperature.collector"
      }
     ]
    }
   ]
  },
  {
   "title": "Outside Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heating.sensors",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "feature",
       "operator": "=",
       "value": "heating.sensors.temperature.outside"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumption Overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "PowerConsumption_Day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.power",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity", "operator": "=", "value": "currentDay" }
     ]
    },
    {
     "alias": "GasConsumption_Day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.gas",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity", "operator": "=", "value": "currentDay" }
     ]
    }
   ]
  },
  { "title": "HKs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "HK $devices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "repeat": "devices",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.circuits",
     "query": "SELECT mean(\"DomesticHotWaterStorageTemperature\") FROM \"viessmann.GazBoiler.Data\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value_string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature_branch", "operator": "=~", "value": "/^$devices$/" },
      { "condition": "AND", "key": "entity", "operator": "=", "value": "name" }
     ]
    }
   ]
  },
  {
   "title": "HK $devices Supply Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "repeat": "devices",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.circuits",
     "query": "SELECT mean(\"DomesticHotWaterStorageTemperature\") FROM \"viessmann.GazBoiler.Data\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature_branch", "operator": "=~", "value": "/^$devices$/" },
      { "condition": "AND", "key": "feature_child", "operator": "=", "value": "sensors.temperature.supply" },
      { "condition": "AND", "key": "entity", "operator": "=", "value": "value" }
     ]
    }
   ]
  },
  {
   "title": "HK $devices States",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "repeat": "devices",
   "targets": [
    {
     "alias": "Mode Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating.circuits",
     "select": [
      [
       { "params": [ "value_string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature_branch", "operator": "=~", "value": "/^$devices$/" },
      { "condition": "AND", "key": "feature_child", "operator": "=", "value": "operating.modes.active" }
     ]
    },
    {
     "alias": "Program Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating.circuits",
     "select": [
      [
       { "params": [ "value_string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature_branch", "operator": "=~", "value": "/^$devices$/" },
      { "condition": "AND", "key": "feature_child", "operator": "=", "value": "operating.programs.active" }
     ]
    },
    {
     "alias": "Pump",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating.circuits",
     "select": [
      [
       { "params": [ "value_string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature_branch", "operator": "=~", "value": "/^$devices$/" },
      { "condition": "AND", "key": "feature_child", "operator": "=", "value": "circulation.pump" }
     ]
    },
    {
     "alias": "FrostProtection",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating.circuits",
     "select": [
      [
       { "params": [ "value_string" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature_branch", "operator": "=~", "value": "/^$devices$/" },
      { "condition": "AND", "key": "feature_child", "operator": "=", "value": "frostprotection" }
     ]
    },
    {
     "alias": "DHW State",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating.circuits",
     "select": [
      [
       { "params": [ "value_boolean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "feature_branch", "operator": "=~", "value": "/^$devices$/" },
      { "condition": "AND", "key": "feature_child", "operator": "=", "value": "operating.modes.dhw" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
   "repeat": "devices",
   "targets": [
    {
     "measurement": "heating.circuits",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Shift" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "feature_branch", "operator": "=~", "value": "/^$devices$/" },
      { "condition": "AND", "key": "feature_child", "operator": "=", "value": "heating.curve" },
      { "condition": "AND", "key": "entity", "operator": "=", "value": "shift" }
     ]
    },
    {
     "measurement": "heating.circuits",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Slope" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "feature_branch", "operator": "=~", "value": "/^$devices$/" },
      { "condition": "AND", "key": "feature_child", "operator": "=", "value": "heating.curve" },
      { "condition": "AND", "key": "entity", "operator": "=", "value": "slope" }
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "SolarCollectorTemp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.solar",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "feature",
       "operator": "=",
       "value": "heating.solar.sensors.temperature.collector"
      },
      { "condition": "AND", "key": "entity", "operator": "=", "value": "value" }
     ]
    },
    {
     "alias": "SolarDHWTemp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.solar",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "feature",
       "operator": "=",
       "value": "heating.solar.sensors.temperature.dhw"
      },
      { "condition": "AND", "key": "entity", "operator": "=", "value": "value" }
     ]
    },
    {
     "alias": "BoilerMain",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.boiler",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "heating.boiler.temperature" }
     ]
    },
    {
     "alias": "BoilerSupply",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heating.boiler",
     "select": [
      [
       { "params": [ "value_number" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "feature",
       "operator": "=",
       "value": "heating.boiler.sensors.temperature.commonSupply"
      }
     ]
    },
    {
     "alias": "BurnerState",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "heating.burners",
     "select": [
      [
       { "params": [ "value_boolean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true
  },
  {
   "title": "Power-consumption  {$consumption_entities}",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 54 },
   "repeat": "consumption_entities",
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "array_index" ], "type": "tag" }
     ],
     "measurement": "heating.power",
     "select": [
      [
       { "params": [ "value_array.idx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "value" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "entity", "operator": "=~", "value": "/^$consumption_entities$/" },
      {
       "condition": "AND",
       "key": "feature",
       "operator": "=",
       "value": "heating.power.consumption.total"
      }
     ]
    }
   ]
  },
  {
   "title": "Gas-consumption  {$consumption_entities}",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 66 },
   "repeat": "consumption_entities",
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "array_index" ], "type": "tag" }
     ],
     "measurement": "heating.gas",
     "select": [
      [
       { "params": [ "value_array.idx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "value" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "heating.gas.consumption.total" },
      { "condition": "AND", "key": "entity", "operator": "=~", "value": "/^$consumption_entities$/" }
     ]
    }
   ]
  }
 ]
}